plugins:
  - jekyll-feed
  - jekyll-sitemap

title: "STM32-base project"
logo: "/assets/img/logos/STM32-base_logo_no_text_transparent.png"
author: "Thomas Gravekamp"
description: >
  The STM32-base project is meant for students and hobbyists. The goal of the
  STM32-base project is to provide a simple and easy to use base project for
  working with STM32 microcontrollers.

mainMenu:
  - name: "Home"
    url: ""
    external: false
  - name: "Guides"
    url: "guides"
    external: false
  - name: "Concepts"
    url: "concepts"
    external: false
  - name: "Boards"
    url: "boards"
    external: false
  - name: "Cheatsheets"
    url: "cheatsheets"
    external: false
  - name: "Github"
    url: "https://github.com/STM32-base"
    external: true
